### PR TITLE
Adding content

### PR DESCRIPTION
**Pull request by StefanIvanov**

### CODE REVIEW

**Review by AutumnKots — APPROVED** [review]
looks good

**Comment by StefanIvanov** [comment]
> looks good

I stumbled on one localization file with some 2000 strings and tried to extract things that would make sense. Now I am not sure what's for a banner and what's for a dialog but tried to somehow organize things. I think we can improve the strings further, I did some changes on my own but feel free to just edit them when you have time @AutumnKots my goal is to have as many examples as possibles so that people start using them as a foundation for their copy in feature designs.

**Comment by StefanIvanov** [comment]
@kckfm1 let's go through the content pieces and make edits wherever necessary

**Review by ghost — APPROVED** [review]

**Comment by StefanIvanov** [comment]
@kckfm1 I know you split this to separate files but I will merge it for now as one json for all dialog types and we can decide what to do later about that :) is this OK for you?

**Comment by kckfm1** [comment]
All is good @StefanIvanov, for now :)

**Pull request merged**
