### PR TITLE
Rename Tokens [BIG]

### PR DESCRIPTION
**Pull request by Ddungyov**

### CODE REVIEW

**Comment by StefanIvanov** [comment]
image

**Comment by StefanIvanov** [comment]
@Ddungyov i see there are 8 conflicts do you want to jump on a quick call together to resolve them before we meet with @qtvdobrin

**Comment by Ddungyov** [comment]
> @Ddungyov i see there are 8 conflicts do you want to jump on a quick call together to resolve them before we meet with @qtvdobrin

I've checked them and those won't be really a conflict

**Comment by StefanIvanov** [comment]
> > @Ddungyov i see there are 8 conflicts do you want to jump on a quick call together to resolve them before we meet with @qtvdobrin
> 
> I've checked them and those won't be really a conflict

Screenshot 2023-07-04 at 17 19 22

You cannot do anything with this branch until they are resolved...

**Comment by StefanIvanov** [comment]
Screenshot 2023-07-06 at 14 22 07

**Comment by StefanIvanov** [comment]
Screenshot 2023-07-06 at 14 24 40

should start with an underscore, not with a dash

**Comment by StefanIvanov** [comment]
Screenshot 2023-07-06 at 14 27 21
Screenshot 2023-07-06 at 14 28 22
Screenshot 2023-07-06 at 14 26 57

I notice inconsistencies with typographies

**Comment by Ddungyov** [comment]
> Screenshot 2023-07-06 at 14 24 40
> should start with an underscore, not with a dash

Those are on purpose, otherwise, the plugin doesn't link the right tokens since they find them identical due to the category name

**Comment by StefanIvanov** [comment]
> 

we have to find a way to work around this ... maybe we can add something like -image_size-xl etc. ...

**Comment by Ddungyov** [comment]
> > 
> 
> we have to find a way to work around this ... maybe we can add something like -image_size-xl etc. ...

great suggestion actually, commited.

**Pull request merged**
